### ISSUE TITLE
一些公共的类是不是过于重复

### ISSUE THREAD

**Issue by zypy333** [OpenDRG/DRG_Java#2]
各个包里都有GroupProxy 类似的类，是不是可以抽成一个基类，用多态比较方便做不同版本切换，改错误也容易一些

另外
GroupProxy里的103行 参数不一致
`checkMessages.putMessage(record.Index, String.format("%s->%s %s",x,zd)); ` 
 130行 转码了两遍
``` 
status=trans(record);  
            if (trans(record)!=null){
```

**Comment by OpenDRG** [comment]
你好，我的设计思路，每一个地区的分组器是完全独立的，他们会编译打包成独立的可执行文件，如dll，jar等，版本切换时，更换这些文件即可。而不需要在GroupProxy层面进行复用

**Comment by OpenDRG** [comment]
你提到的两处错误，请给出具体的路径和文件，我来修正
